baseURL = "https://bjohnstonpainting.com/"
languageCode = "en-us"
title = "Bill Johnston Painting"
theme = "bjpainting"
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 100
    [[menu.main]]
        identifier = "Services"
        name = "Services"
        weight = 80